name: text_coloration
description: "search part of the text and colored with color"
version: 0.3.0
homepage: https://github.com/liodali/text_coloration

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0